name: InferFlux CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest

    container:
      image: golang:1.22.8
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        run: |
          make lint

      - name: Test
        run: |
          make test    
